# outputs.tf
# Generated by Enhanced Terraform Generator

output "resource_group_id" {
  description = "The ID of the resource group"
  value       = module.base-vm.resource_group_id
}

output "vm_ids" {
  description = "The IDs of the virtual machines"
  value       = module.base-vm.vm_ids
}

output "vm_private_ips" {
  description = "The private IP addresses of the virtual machines"
  value       = module.base-vm.vm_private_ips
}

output "key_vault_id" {
  description = "The ID of the Key Vault"
  value       = module.base-vm.key_vault_id
}

output "key_vault_uri" {
  description = "The URI of the Key Vault"
  value       = module.base-vm.key_vault_uri
}
