# variables.tf
# Generated by Enhanced Terraform Generator

variable "spn" {
  type        = string
  default     = null
  description = "Display name for Service Principal"
}

variable "resource_group_name" {
  type    = string
  default = null
}

variable "location" {
  type     = string
  default  = "here"
  nullable = false
  validation {
    condition = contains(
      [
        "WEST US",
        "WEST US 2",
        "WEST US 3",
        "EAST US",
        "EAST US 2",
        "CENTRAL US",
        "NORTH CENTRAL US",
        "SOUTH CENTRAL US"
      ], var.location
    )
    error_message = "Invalid location. Please use a valid Azure region."
  }
}

variable "existing_application_security_groups" {
  type    = map(any)
  default = {}
}

variable "application_security_groups" {
  type = map(object({
    name = string
  }))
  default = {}
}

variable "key_vault" {
  type = object({
    name                       = string
    sku_name                   = string
    soft_delete_retention_days = number
    public_network_access      = bool
    snet_key                   = string
    key_name                   = string
  })
}

variable "user_assigned_identity_name" {
  type = string
}

variable "disk_encryption_set_name" {
  type = string
}

variable "subnets" {
  type = map(object({
    resource_group_name         = string
    virtual_network_name        = string
    network_security_group_id   = string
    route_table_id              = string
    name                        = string
    prefixes                    = list(string)
    service_endpoints           = list(string)
  }))
  default = {}
}

variable "existing_subnets" {
  type    = map(any)
  default = {}
}

variable "private_endpoints" {
  type = map(object({
    name              = string
    subresource_names = list(string)
    snet_key          = string
    asg_key           = string
  }))
  default = {}
}

variable "admin_username" {
  type    = string
  default = "azureadmin"
}

variable "admin_password" {
  type      = string
  sensitive = true
  default   = null
}

variable "vm_list" {
  type = map(object({
    name              = string
    size              = string
    zone              = optional(string)
    image_os          = string
    marketplace_image = bool
    image_urn         = string
    ip_allocation     = string
    ip_address        = optional(string)
    identity_type     = string
    os_disk_size      = number
    os_disk_type      = string
    os_disk_tier      = optional(string)
    data_disk_sizes   = list(number)
    data_disk_type    = string
    snet_key          = string
    asg_key           = string
    tags              = map(string)
  }))
  default = {}
}

variable "network_security_rules" {
  type = object({
    resource_group_name         = string
    network_security_group_name = string
    rules = list(object({
      name                        = string
      priority                    = number
      direction                   = string
      access                      = string
      protocol                    = string
      source_port_range           = string
      destination_port_ranges     = list(string)
      source_asg                  = string
      destination_asg             = string
      description                 = string
    }))
  })
}

variable "common_tags" {
  type    = map(string)
  default = {}
}

variable "resource_specific_tags" {
  type    = map(map(string))
  default = {}
}
