#!/bin/bash
# Terraform Deployment Script
# Generated by Excel to Terraform Automation Pipeline

set -e

echo "=========================================="
echo "Terraform Infrastructure Deployment"
echo "=========================================="

# Check if terraform is installed
if ! command -v terraform &> /dev/null; then
    echo "ERROR: Terraform not found. Please install Terraform."
    exit 1
fi

echo "Terraform version: $(terraform --version)"

# Initialize Terraform
echo "Initializing Terraform..."
terraform init

# Validate configuration
echo "Validating Terraform configuration..."
terraform validate

# Plan deployment
echo "Creating deployment plan..."
terraform plan -out=tfplan

# Show plan summary
echo "Deployment plan created. Review the plan above."
echo ""
echo "To deploy the infrastructure, run:"
echo "  terraform apply tfplan"
echo ""
echo "To destroy the infrastructure, run:"
echo "  terraform destroy"
echo ""

# Ask for confirmation
read -p "Do you want to proceed with deployment? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Deploying infrastructure..."
    terraform apply tfplan
    echo "Deployment completed successfully!"
else
    echo "Deployment cancelled."
fi
