#!/bin/bash
# validate.sh
# Generated by Enhanced Terraform Generator

set -e

echo "========================================"
echo "Terraform Configuration Validation"
echo "========================================"

# Check if Terraform is installed
if ! command -v terraform &> /dev/null; then
    echo "ERROR: Terraform is not installed"
    exit 1
fi

echo "✓ Terraform is installed: $(terraform version | head -n1)"

# Initialize Terraform
echo ""
echo "Initializing Terraform..."
terraform init -backend=false

# Validate configuration
echo ""
echo "Validating Terraform configuration..."
if terraform validate; then
    echo "✓ Configuration is valid"
else
    echo "✗ Configuration validation failed"
    exit 1
fi

# Format check
echo ""
echo "Checking Terraform formatting..."
if terraform fmt -check=true -diff; then
    echo "✓ Configuration is properly formatted"
else
    echo "✗ Configuration needs formatting"
    echo "Run 'terraform fmt' to fix formatting"
fi

echo ""
echo "========================================"
echo "Validation Complete"
echo "========================================"
